core/urls.py
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
)
from django.urls import path, reverse_lazy

from core.forms import BasePasswordChangeForm, BasePasswordResetForm
from core.models import ParameterForBase
from core.views import IndexTemplateView, BaseLoginView, BaseLogoutView, BasePasswordResetCompleteView

app_name = 'core'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('login/', BaseLoginView.as_view(), name='login'),
    path('logout/', BaseLogoutView.as_view(), name='logout'),

    path('password/change/', PasswordChangeView.as_view(
        template_name='outside_template/registration/password_change_form.html',
        success_url=reverse_lazy('core:password_change_done'),
        form_class=BasePasswordChangeForm,
        extra_context={'parameter': ParameterForBase.objects.first}), name='password_change'),

    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='outside_template/registration/password_change_done.html',
        extra_context={'parameter': ParameterForBase.objects.first}), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='outside_template/registration/password_reset_form.html',
        success_url=reverse_lazy('core:password_reset_done'),
        form_class=BasePasswordResetForm,
        extra_context={'parameter': ParameterForBase.objects.first},
        email_template_name='outside_template/registration/password_reset_email.html'), name="password_reset"),

    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='outside_template/registration/password_reset_done.html',
        extra_context={'parameter': ParameterForBase.objects.first}), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='outside_template/registration/password_reset_confirm.html',
        success_url=reverse_lazy('core:password_reset_complete'),
        extra_context={'parameter': ParameterForBase.objects.first} ), name="password_reset_confirm"),

    path('reset/done/', BasePasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

core/templates/includes/filters.html
{% load static boilerplate_base %}
{% if filters %}
    <div class="form-group my-0 py-0">
        {% comment %}Bloco filtro para subscrever os filtros que podem ser aplicados na listagem{% endcomment %}
        <!-- Percorrendo todos os filtros -->
        <div class="row my-0 py-0">
            {% for filter in filters %}
                <div class="col-sm">
                    {% for key_filter, value_filter in filter.items %}
                        <label for="{{ key_filter }}">{{ value_filter.label}}: &nbsp;</label>
{#                       if trata apena os tipos de data#}
                        {% if  value_filter.type_filter == 'DateField' or value_filter.type_filter == 'DateTimeField' %}
                            <div class="btn-group date-filter w-100" role="group">
                                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="id-{{ key_filter }}-select-button">
                                    <span class="sr-only">Selecione</span>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="id-{{ key_filter }}-select-list" >
                                    {% set is_parametro_in_query = False %}
                                    {% for item in value_filter.list %}
{#                                        verifica se tem o elemento nos parametros que veio da query#}
                                        {% if key_filter|add:item.choice_id|stringformat:"s"|in_list:query_params_filters.keys%}
                                            {% set is_parametro_in_query = True %}
                                            {% for key_param_filter, value_param_filter in query_params_filters.items %}
                                                {% if key_param_filter|split:'__'|first == key_filter %}
                                                    {% if item.choice_id|split:'__'|last|stringformat:"s" == key_param_filter|split:'__'|last|stringformat:"s" %}
                                                        <div class="dropdown-item active"  data-id-input="id-{{ key_filter }}" data-prefix-filter="{{ item.choice_id }}" >{{ item.choice_label }}</div>
                                                    {% else %}
                                                        <div class="dropdown-item" data-id-input="id-{{ key_filter }}" data-prefix-filter="{{ item.choice_id }}" >{{ item.choice_label }}</div>
                                                    {% endif %}
                                                {% endif %}
                                            {% empty %}
                                                <div class="dropdown-item"  data-id-input="id-{{ key_filter }}" data-prefix-filter="{{ item.choice_id }}" >{{ item.choice_label }}</div>
                                            {% endfor %}
                                        {% else %}
                                            <div class="dropdown-item" data-id-input="id-{{ key_filter }}" data-prefix-filter="{{ item.choice_id }}" >{{ item.choice_label }}</div>

                                        {% endif %}
                                    {% endfor %}

                                </div>

                                {% if is_parametro_in_query %}
                                    {% for key_param_filter, value_param_filter in query_params_filters.items %}
                                         {% if key_param_filter|split:'__'|first == key_filter %}
                                            <input type="text" style="width: 150px!important;" class="form-control {{ value_filter.type_filter|lower  }}"
                                               name="{{ key_param_filter|default:key_filter }}" id="id-{{ key_filter }}" value=" {{ value_param_filter.0}}">
                                         {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <input type="text" style="width: 150px!important;" class="form-control {{ value_filter.type_filter|lower  }}"
                                               name="{{ key_filter|add:value_filter.list.0.choice_id }}" id="id-{{ key_filter }}" >
                                {% endif %}

                                <div class="input-group-btn">
                                    <button class="btn btn-outline-secondary" id="id-{{ key_filter }}-button" type="button" onclick="this.form.submit();">
                                        Filtrar
                                    </button>
                                </div>
                            </div>

{#                       else trata apena os tipos que NÃO são data#}
                        {% else %}
                            <select class="form-control" name="{{ key_filter }}" id="id_{{ key_filter }}" onchange="this.form.submit();">
                                <option value="None">Selecione</option>
                                {% for item in value_filter.list %}
                                    <!-- O Filtro é uma ForeingKey -->
                                    {% if value_filter.type_filter == 'ForeignKey' and item.pk %}
                                        {% for key_param_filter, value_param_filter in query_params_filters.items %}
                                            {% if key_param_filter == key_filter %}
                                                {% if item.pk|stringformat:"s" == value_param_filter.0 %}
                                                    <option value="{{ item.pk }}" selected="selected">{{ item }}</option>
                                                {% else %}
                                                    <option value="{{ item.pk }}">{{ item }}</option>
                                                {% endif %}
                                            {% endif %}
                                        {% empty %}
                                            <option value="{{ item.pk }}">{{ item }}</option>
                                        {% endfor %}
                                    <!-- O Filtro possui o atributo Choice -->
                                    {% elif value_filter.type_filter == 'ChoiceField' and item.choice_id is not None%}
                                        {% for key_param_filter, value_param_filter in query_params_filters.items %}
                                            {% if key_param_filter == key_filter %}
                                                {% if item.choice_id|stringformat:"s" == value_param_filter.0 %}
                                                    <option value="{{ item.choice_id }}" selected="selected">{{ item.choice_label }}</option>
                                                {% else %}
                                                    <option value="{{ item.choice_id }}">{{ item.choice_label }}</option>
                                                {% endif %}
                                            {% endif %}
                                        {% empty %}
                                            <option value="{{ item.choice_id }}">{{ item.choice_label }}</option>
                                        {% endfor %}

                                    {% else %}
                                        <!-- O Filtro não é ForeingKey -->
                                        {% for key_param_filter, value_param_filter in query_params_filters.items %}
                                            <!-- Verificando se foi aplicado algum filtro para recuperar o valor dele e atruibuir ao campo -->
                                            {% if key_param_filter == key_filter and item %}
                                                {% if item|stringformat:"s" == value_param_filter.0 %}
                                                    <option value="{{ item }}" selected="selected">{{ item }}</option>
                                                {% else %}
                                                    <option value="{{ item }}">{{ item }}</option>
                                                {% endif %}
                                            {% endif %}
                                        {% empty %}
                                            <option value="{{ item }}">{{ item }}</option>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </select>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

core/templates/includes/menu-lateral.html
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="mainNav">
    <a class="navbar-brand" href="/">
        {% block titulosistema %} Prefeitura Municipal de Palmas{% endblock titulosistema %}
      </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
    {#    inicia o menu superior#}
        <ul class="navbar-nav navbar-sidenav">
            {% for app in apps %}
                <li class="nav-item dropdown" data-toggle="tooltip" data-placement="right" title="{{ app.name_app }}">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapse{{ forloop.counter }}">
                        <i class="fa fa-map"></i>
                        <span class="nav-link-text">{{ app.name_app }}</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapse{{ forloop.counter }}">
                        {% for app_model in app.models_app %}
                            <li>
                                <a href="{% url app_model.url_list_model %}">{{ app_model.name_model }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
{#    termina o menu lateral#}

{#    inicia o menu superior#}
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item" id="sidenavTogglerLi">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left text-white"></i>
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="nav-item nav-link" href="#"></a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
{#            <li class="nav-item dropdown">#}
{#                <a class="nav-link dropdown-toggle mr-lg-2" href="#" id="messagesDropdown" data-toggle="dropdown"#}
{#                   aria-haspopup="true" aria-expanded="false">#}
{#                   <i class="fas fa-envelope"></i>#}
{#                    <span class="d-lg-none">Mensagens#}
{#                <span class="badge badge-pill badge-primary">12 Novas</span>#}
{#              </span>#}
{#                    <span class="new-indicator text-primary d-none d-lg-block">#}
{#                <i class="fa fa-fw fa-circle"></i>#}
{#                <span class="number">12</span>#}
{#              </span>#}
{#                </a>#}
{#                <div class="dropdown-menu" aria-labelledby="messagesDropdown">#}
{#                    <h6 class="dropdown-header">Novas mensagens:</h6>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                        <strong>David Miller</strong>#}
{#                        <span class="small float-right text-muted">11:21 AM</span>#}
{#                        <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome!#}
{#                            These messages clip off when they reach the end of the box so they don't overflow over to#}
{#                            the sides!#}
{#                        </div>#}
{#                    </a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                        <strong>Jane Smith</strong>#}
{#                        <span class="small float-right text-muted">11:21 AM</span>#}
{#                        <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00#}
{#                            instead of 4:00. Thanks!#}
{#                        </div>#}
{#                    </a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                        <strong>John Doe</strong>#}
{#                        <span class="small float-right text-muted">11:21 AM</span>#}
{#                        <div class="dropdown-message small">I've sent the final files over to you for review. When#}
{#                            you're able to sign off of them let me know and we can discuss distribution.#}
{#                        </div>#}
{#                    </a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item small" href="#">#}
{#                        View all messages#}
{#                    </a>#}
{#                </div>#}
{#            </li>#}
{#            <li class="nav-item dropdown">#}
{#                <a class="nav-link dropdown-toggle mr-lg-2" href="#" id="alertsDropdown" data-toggle="dropdown"#}
{#                   aria-haspopup="true" aria-expanded="false">#}
{#                    <i class="fa fa-fw fa-bell"></i>#}
{#                    <span class="d-lg-none">Alerts#}
{#                <span class="badge badge-pill badge-danger">6 New</span>#}
{#              </span>#}
{#                    <span class="new-indicator text-danger d-none d-lg-block">#}
{#                <i class="fa fa-fw fa-circle"></i>#}
{#                <span class="number">6</span>#}
{#              </span>#}
{#                </a>#}
{#                <div class="dropdown-menu" aria-labelledby="alertsDropdown">#}
{#                    <h6 class="dropdown-header">New Alerts:</h6>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                <span class="text-success">#}
{#                  <strong>#}
{#                    <i class="fa fa-long-arrow-up"></i>#}
{#                    Status Update</strong>#}
{#                </span>#}
{#                        <span class="small float-right text-muted">11:21 AM</span>#}
{#                        <div class="dropdown-message small">This is an automated server response message. All systems#}
{#                            are online.#}
{#                        </div>#}
{#                    </a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                <span class="text-danger">#}
{#                  <strong>#}
{#                    <i class="fa fa-long-arrow-down"></i>#}
{#                    Status Update</strong>#}
{#                </span>#}
{#                        <span class="small float-right text-muted">11:21 AM</span>#}
{#                        <div class="dropdown-message small">This is an automated server response message. All systems#}
{#                            are online.#}
{#                        </div>#}
{#                    </a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="#">#}
{#                <span class="text-success">#}
{#                  <strong>#}
{#                    <i class="fa fa-long-arrow-up"></i>#}
{#                    Status Update</strong>#}
{#                </span>#}
{#                        <span class="small float-right text-muted">11:21 AM</span>#}
{#                        <div class="dropdown-message small">This is an automated server response message. All systems#}
{#                            are online.#}
{#                        </div>#}
{#                    </a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item small" href="#">#}
{#                        View all alerts#}
{#                    </a>#}
{#                </div>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <form class="form-inline my-2 my-lg-0 mr-lg-2">#}
{#                    <div class="input-group">#}
{#                        <input type="text" class="form-control" placeholder="Buscar...">#}
{#                        <span class="input-group-btn">#}
{#                  <button class="btn btn-success" type="button">#}
{#                    <i class="fa fa-search"></i>#}
{#                  </button>#}
{#                </span>#}
{#                    </div>#}
{#                </form>#}
{#            </li>#}




            {% if user.is_authenticated %}
                <li class="nav-item">
                    <div  class="navbar-link mr-4">
                        {% if user.first_name %}
                            Olá {{ user.first_name }} {{ user.last_name }}
                        {% elif user.username  %}
                             Olá {{ user.username }}
                        {% endif %}
                    </div>
                </li>

                <li class="nav-item nav-space">
                    <a class="navbar-link" href="{% url 'core:password_change' %}"> Alterar Senha</a>
                </li>

                <li class="nav-item nav-space">
                    <a href="#" class="navbar-link" data-toggle="modal" data-target="#exampleModal">
                        <i class="fas fa-sign-out-alt"></i> Sair</a>
                </li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Log in</a></li>
            {% endif %}
        </ul>

{#    termina o menu superior#}
    </div>
</nav>

core/templates/includes/search.html
{% load static boilerplate_base %}
 <div class="row mr-2">
    <div class="col-11">
        <input type="text" class="form-control" id="pesquisa" value="{{ query_params_q }}" name="q" placeholder="Digite o termo para filtrar" aria-label="Digite o termo para filtrar">

    </div>
    <div class="col-1">
        <button type="submit" class="btn btn-primary btn-inline-form"><i class="fa fa-search"></i> Pesquisar </button>
    </div>
</div>