core/urls.py
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
)
from django.urls import path, reverse_lazy

from core.forms import BasePasswordChangeForm, BasePasswordResetForm
from core.models import ParameterForBase
from core.views import IndexTemplateView, BaseLoginView, BaseLogoutView, BasePasswordResetCompleteView

app_name = 'core'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('login/', BaseLoginView.as_view(), name='login'),
    path('logout/', BaseLogoutView.as_view(), name='logout'),

    path('password/change/', PasswordChangeView.as_view(
        template_name='outside_template/registration/password_change_form.html',
        success_url=reverse_lazy('core:password_change_done'),
        form_class=BasePasswordChangeForm,
        extra_context={'parameter': ParameterForBase.objects.first}), name='password_change'),

    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='outside_template/registration/password_change_done.html',
        extra_context={'parameter': ParameterForBase.objects.first}), name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='outside_template/registration/password_reset_form.html',
        success_url=reverse_lazy('core:password_reset_done'),
        form_class=BasePasswordResetForm,
        extra_context={'parameter': ParameterForBase.objects.first},
        email_template_name='outside_template/registration/password_reset_email.html'), name="password_reset"),

    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='outside_template/registration/password_reset_done.html',
        extra_context={'parameter': ParameterForBase.objects.first}), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='outside_template/registration/password_reset_confirm.html',
        success_url=reverse_lazy('core:password_reset_complete'),
        extra_context={'parameter': ParameterForBase.objects.first} ), name="password_reset_confirm"),

    path('reset/done/', BasePasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

core/templates/outside_template/base.html
{% load staticfiles %}{% load boilerplate_base %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Prefeitura de Palmas{% endblock title %}</title>

    <!-- Bootstrap 4 CSS -->
{#    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.min.css' %}">#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    
    <!-- Jasny Bootstrap -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">

    <!-- Date Picker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.min.css">

    <!-- Importando base css -->
    <link rel="stylesheet" href="{% static 'outside/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'outside/css/sb-admin.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'outside/images/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css" />
    {% block extra_css %}{% endblock extra_css %}


    <!-- jQuery -->
{#    <!-- jquery ele dá problema nos inlines caso ele fique no final do body -->#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    {# pega os css e js dos plugins add #}
    {{ form.media }}

</head>

<body class="fixed-nav sidenav-toggled" id="page-top">

{% block body %}
    <div id="div-content-menu">
      <!-- Menu lateral -->
        {% block navbar %}
            {% include 'includes/menu-lateral.html' %}
        {% endblock %}
    </div>


    <div class="content-wrapper py-3">
    <!-- Conteúdo -->
        <div class="container-fluid mt-50">
            <div id="div-breacrumb">
                {% block breadcrumb %}
                    {% if breadcrumbs %}
                        <ol class="breadcrumb">
                            {% for breadcrumb in breadcrumbs %}
                                <li class="breadcrumb-item">
                                    {% if breadcrumb.url %}
                                        <a href="{{ breadcrumb.url }}">{{ breadcrumb.slug }}</a>
                                    {% else %}
                                        {{ breadcrumb.slug }}
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                {% endblock breadcrumb %}
            </div>

            <div id="conteudo">
                {% block messages %}
                    {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class="alert {% if message.extra_tags %}alert-{{ message.extra_tags }}{% elif message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show"
                                     role="alert">
                                  {{ message|safe }}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endblock messages %}
                {% block content %}
                    {% block related_fields %}
                    <!-- Bloco para mostrar os campos com relacionamento na tela de Delete -->
                    {% endblock related_fields %}
                {% endblock content %}

            </div>
        </div>
    </div>

    <!-- Logout Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sair do sistema?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Clique em "Logout" abaixo se você quer encerrar sua sessão.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <a   class="btn btn-danger" href="{% url 'core:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

    <!-- Pooper -->
    <script src="{% static 'outside/popper/popper.js' %}"></script>

    <!-- Moments -->
    <script src="{% static 'outside/datepicker/js/moments.js' %}"></script>

    <!-- Moments -->
    <script src="{% static 'outside/plugins/js/knob.js' %}"></script>

    <!-- Bootstrap 4 core Javascript -->
    <script src="{% static 'bootstrap4/js/bootstrap.min.js'%}"></script>

    <!-- Jasny Bootstrap -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

    <!-- DatePicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>

    <!-- DatePicker pt-BR language -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/locales/bootstrap-datepicker.pt-BR.min.js"></script>

    <!-- DataTables -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>


    <!-- JS -->
    <script src="{% static 'outside/js/sb-admin.js' %}"></script>

    <script src="{% static 'outside/js/base.js' %}"></script>

{#    <!-- jquery.formset ele dá muito problema se colocado em outro lugar por isso ele sempre tem que ficar aqui, abaixo do admin e do base -->#}
    <script src="{% static 'outside/js/jquery.formset.js' %}" ></script>

    <!-- Js responsável pelas funções dos inlines -->
    <script src="{% static 'outside/js/inline.js' %}" ></script>


{% block extra_js %}{% endblock extra_js %}


</body>


</html>

core/templates/outside_template/base_delete.html
{% extends "outside_template/base.html" %}
{% load staticfiles %}
{% load boilerplate_base i18n %}
{% block content %}
    {% if has_delete_permission %}
        <div class="container-fluid container-margin">
            {% if perms_lacking %}
                <p>{% blocktrans with escaped_object=object %}A remoção de '{{ model_name }}' {{ escaped_object }} pode resultar na remoção de objetos relacionados, mas sua conta não tem a permissão para remoção dos seguintes tipos de objetos:{% endblocktrans %}</p>
                <div class="alert alert-warning" role="alert">
                    <ul style="margin-bottom: 0 !important;">
                        {% for obj in perms_lacking %}
                            <li>{{ obj }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if protected %}
                <p>{% blocktrans with escaped_object=object %}Excluir o <b> '{{model_name}}' {{escaped_object}} </b> exigiria a exclusão dos seguintes relacionamentos protegidos: {% endblocktrans%} </p>
                <div class="alert alert-warning" role="alert">
                    <ul style="margin-bottom: 0 !important;">
                        {% for obj in protected %}
                            <li>{{ obj }}</li>
                        {% endfor %}
                    </ul>
                </div>

            {% endif %}
           
            {% if not protected and not perms_lacking %}
                <h3>{% block tituloapp %} Apagar: {{ object }} ? {% endblock tituloapp %}</h3>
                <p>{% blocktrans with escaped_object=object %}Tem certeza de que deseja excluir o objeto <b>{{ model_name }} "{{ escaped_object }}"</b>? Todos os seguintes objetos relacionados serão excluídos:{% endblocktrans %}</p>

                {% block related_fields %}
                    <!-- Bloco para exibir os campos que possuem relacionamento
                    com o registro que está sendo excluído -->
                    <div class="container-fluid container-margin">
                        {% for field in many_fields %}
                            {% if field.1.all %}
                                {% if forloop.first %}
                                    <h4>Todos os itens abaixo também serão apagados.</h4>
                                {% endif %}
                                <div class="alert alert-warning" role="alert">
                                    <h4 class="alert-heading">{{ field.0|capfirst }}</h4>
                                    <ul>
                                        {% for item in field.1.all %}
                                            <li>{{ item }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endblock related_fields %}
                {% block contentform %}
                    <form class="needs-validation was-validated" method="post" novalidate>
                        {% csrf_token %}
                        <div class="row justify-content-between">
                        {% block buttonbar %}
                            <div class="col-6">
                                <a href="{% url url_list %}" class="btn btn-primary"> <i class="fas fa-arrow-left"></i> Cancelar exclusão.</a>
                            </div>
                            <div class="col-5 text-right">
                                 {% if has_delete_permission %}
                                    <button type="submit" class="btn btn-danger "><i class="fas fa-trash"></i> Confirma exclusão?</button>
                                {% endif %}
                            </div>
                            {% endblock buttonbar %}
                        </div>
                    </form>
                {% endblock contentform %}
                {% else %}
                    {% if has_delete_permission or protected %}
                    <div class="col-6">
                        <a href="{% url url_list %}" class="btn btn-primary">
                            <i class="fas fa-arrow-left"></i> Voltar
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    {% else %}
        <div class="alert alert-danger" role="alert">
          <h4 class="alert-heading"> Voce não tem permisão para acessar essa pagina!</h4>
        </div>
    {% endif %}

 {% endblock content %}

core/templates/outside_template/base_detail.html
{% extends "outside_template/base.html" %}
{% load staticfiles %}{% load boilerplate_base %}

{% block content %}
    {% if has_add_permission or  has_change_permission or  has_delete_permission %}

            <div class="row">
                <div class="col-md-10">
                    <h2>{% block tituloapp %}Detalhe {{ model_name }}{% endblock tituloapp %}</h2>
                </div>
                <div class="col-md-2">
                    <div class="btn-group" role="group">
                        <a class="btn btn-default btn-lg" data-toggle="tooltip" data-placement="bottom" title="Imprimir"><i class="fa fa-print" aria-hidden="true"></i></a>
                        <a href="{% url url_update object.pk %}" class="btn btn-default btn-lg" data-toggle="tooltip" data-placement="bottom" title="Editar"><i class="fa fa-pencil" aria-hidden="true"></i> </a>
                    </div>
                </div>
            </div>

            <div class="card-deck">
                {% for field in object_list %}
                    {% if not forloop.first and forloop.counter0|divisibleby:2 %}
                        </div>
                        <div class="card-deck">
                    {% endif %}
                    <div class="card m-1">
                        <div class="card-body">
                            <strong>{{ field.0|capfirst }}: </strong>
                            {% if not field.1 is None and  field.1 != '' %}
                                <p class="card-text">
                                    {{ field.1|safe }}
                                </p>
                            {% else %}
                                 <p class="card-text" style="color: red">
                                    Não contem o valor
                                </p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="card-deck">
                <div class="card m-1">
                    <div class="card-body">
                        {% for field in many_fields  %}
                               <strong>{{ field.0|capfirst }}</strong><br>
                             <div class="card-deck">
                                {% for obj in field.1.all %}
                                    {% if not forloop.first and forloop.counter0|divisibleby:2 %}
                                        </div>
                                        <div class="card-deck">
                                    {% endif %}
                                    <div class="card m-1">
                                        <div class="card-body">
                                            <p class="card-text">
                                                {{ obj|safe }}
                                            </p>
                                        </div>
                                    </div>
                                {% endfor %}
                             </div>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <div class="row justify-content-between">
                {% block buttonbar %}
                    <div class="col-md-12 text-right" >
                        <a href="{% url url_list %}" class="btn btn-primary">Voltar</a>
                    </div>
                {% endblock buttonbar %}
            </div>
    {% else %}
             <div class="alert alert-danger" role="alert">
              <h4 class="alert-heading"> Voce não tem permisão para acessar essa pagina!</h4>
            </div>
    {% endif %}
 {% endblock content %}

core/templates/outside_template/base_list.html
{% extends "outside_template/base.html" %}
{% load boilerplate_base %}

{% block content %}
    {% if has_add_permission or  has_change_permission or  has_delete_permission %}
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <h2>{% block titulo_template %}List {{ model_name }}{% endblock %}</h2>
                </div>
        </div>

        <!-- Filter and Search Area -->
        <form id="id_search_and_filter">
            {% block containersearchandfilter %}
                <div class="row my-0 py-0 search">
                    <div class="col-12">
                        {% block search %}
                            {% include 'includes/search.html' %}
                        {% endblock search %}
                    </div>
                    <div class="col-12 mt-3 filters ">
                        {% block filter %}
                            {% include 'includes/filters.html' %}
                        {% endblock filter %}
                    </div>
                    {% block buttonfilter %}
                        <div class="col-12 text-right mt-3" >
                            <button id="id_clean_filter"  class="btn btn-danger"> Limpar Filtros</button>
                        </div>
                    {% endblock buttonfilter %}
                </div>
            {% endblock containersearchandfilter %}
        </form>
        <!-- End Filter and Search Area -->

            <!-- Table Area -->
            <div class="row mt-3 mb-0 pb-0">
                <div class="col">
                    <div class="row">
                        <div id="div-table" class="col-md-12">
                        {% block tableblock %}
                            {% if object_list|length > 0 and display|length > 0 %}
                                <table id="table-item" class="table table-striped">
                                    <thead>
                                    <tr>
                                        <!-- Percorrendo os list_display q serão exibidos para criar os títulos das colunas -->
                                        {% for header in display %}
                                            {% if header == 'pk' or header == 'id' %}
                                                <th>Opções</th>
                                            {% else %}
                                                <th>{{ header|capfirst }}</th>
                                            {% endif %}
                                        {% empty %}

                                        {% endfor %}
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for value in object_list %}
                                        <tr>
                                            {% for item_key, item_value in value.items %}
                                                    {% if item_key == 'pk'   %}
                                                         <td align="middle" style="width: 160px !important;">
                                                            <a href="{% url url_detail value.pk %}" class="btn btn-info btn-sm"
                                                               data-toggle="tooltip" data-placement="right" title="Visualizar Registro"><i class="fa fa-eye" ></i></a>
                                                            {% if has_change_permission %}
                                                                <a href="{% url url_update value.pk %}" class="btn btn-warning btn-sm"
                                                                data-toggle="tooltip" data-placement="right" title="Editar Registro" ><i class="far fa-edit"></i></a>
                                                            {% endif %}
                                                            {% if has_delete_permission %}
                                                                <a href="{% url url_delete value.pk %}" class="btn btn-danger btn-sm"
                                                                data-toggle="tooltip" data-placement="right" title="Apagar Registro" ><i class="fas fa-trash"></i></a>
                                                            {% endif %}
                                                         </td>
                                                    {% elif item_key == 'id'  %}
                                                        <td align="middle" style="width: 160px !important;">
                                                            <a href="{% url url_detail value.id %}" class="btn btn-info btn-sm"
                                                               data-toggle="tooltip" data-placement="right" title="Visualizar Registro" ><i class="fa fa-eye" ></i></a>
                                                            {% if has_change_permission %}
                                                                <a href="{% url url_update value.id %}"  class="btn btn-warning btn-sm"
                                                                data-toggle="tooltip" data-placement="right" title="Editar Registro" ><i class="far fa-edit"></i></a>
                                                            {% endif %}
                                                            {% if has_delete_permission %}
                                                                <a href="{% url url_delete value.id %}" class="btn btn-danger btn-sm"
                                                                data-toggle="tooltip" data-placement="right" title="Apagar Registro" ><i class="fas fa-trash"></i></a>
                                                            {% endif %}
                                                        </td>
                                                    {% else %}
                                                        <td>
                                                            {{ item_value }}
                                                        </td>
                                                    {% endif %}
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                    {% if is_paginated %}
                                        <tfoot>
                                            <tr>
                                                <td colspan="{{ display|length }}">
                                                    <ul class="pagination justify-content-center">
                                                        {% if page_obj.has_previous %}
                                                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ url_pagination }}">Anterior</a></li>
                                                        {% endif %}
                                                        {% for i  in paginator.page_range %}
                                                            {% if page_obj.number != i and i < page_obj.number and i == 4 and page_obj.number|add:-2 > 4 or  page_obj.number != i and i > page_obj.number and i == page_obj.paginator.num_pages|add:-3  and page_obj.number|add:2 < page_obj.paginator.num_pages|add:-3 %}
                                                                <li class="page-item disabled" ><a class="page-link">...</a></li>
                                                            {% else %}
                                                                {% if i >= page_obj.number|add:-2 and i <= page_obj.number|add:2 or i <= 3 or i >= page_obj.paginator.num_pages|add:-2%}
                                                                    <li class="page-item {% if page_obj.number == i %} active {% endif %}">
                                                                        <a class="page-link" href="?page={{ i }}&{{ url_pagination }}">{{ i }}</a>
                                                                    </li>
                                                                {% endif %}
                                                            {% endif %}
                                                        {% endfor %}
                                                        {% if page_obj.has_next %}
                                                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ url_pagination }}">Próximo</a></li>
                                                        {% endif %}
                                                    </ul>
                                                </td>
                                            </tr>
                                        </tfoot>
                                    {% endif %}
                                </table>
                            {% else %}
                                <div class="alert alert-info" role="alert">
                                    {% block mensagem_info %}
                                        Nenhum item encontrado.
                                    {% endblock %}
                                </div>
                            {% endif %}
                             {% block buttonbar %}
                                    <div class="col-md-12 text-right" >
                                         {% if has_add_permission %}
                                            <a href="{% url url_create %}" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> Adicionar</a>
                                         {% endif %}
                                    </div>
                             {% endblock %}
                        {% endblock tableblock %}
                    </div>
                </div>
                </div>
            </div>
            <!-- End Table Area -->
            <!-- Pagination and actions buttons -->
            <div class="row pt-0 mt-0">
                <div class="col-12 text-right mr-0 pr-0">
                    {% block actionbuttons %}
                    {% endblock actionbuttons %}
                </div>
            </div>
        </div>
    {% else %}
         <div class="alert alert-danger" role="alert">
          <h4 class="alert-heading"> Voce não tem permisão para acessar essa pagina!</h4>
        </div>
    {% endif %}
{% endblock content %}

core/templates/outside_template/index.html
{% extends "outside_template/base.html" %}
{% load boilerplate_base %}

{% block content %}

        {% if redirect_to %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {% if user.is_authenticated %}
                <p> Sua conta não tem acesso a esta página. Para prosseguir, por favor faça o login com uma conta que tenha acesso.</p>
                {% else %}
                <p>Por favor, faça o login para ver esta página.</p>
            {% endif %}
                <button type="button" class="close" data-dismiss="alert"
                    aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}

       <div class="card-deck">
            {% for app in apps %}
               {% if not app_name or app_name and app_name is app.name_app  %}
                   {% if not forloop.first and forloop.counter0|divisibleby:2 %}
                        </div>
                        <div class="card-deck">
                   {% endif %}
                   <div class="card">
                        <div class="card-header">
                            {{ app.verbose_name_app }}
                        </div>
                        <div class="card-body">
                            <div class="row">
                                {% for model in app.models_app %}
                                <div class="col-6">
                                    <a class="btn btn-outline-primary btn-block"
                                       style="white-space:normal !important;"
                                       href="{% url model.url_list_model %}">
                                        {{ model.name_model }}
                                    </a>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

{% endblock content %}